### ISSUE TITLE
Fail to install epinio on arm64

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1473] opened 2022-05-19 13:04 UTC
Apparently, buildpacks seem to be ready for ARM so I wanted to give it a try on my raspberry 4 with raspian64.
But it quickly failed because `epinio-ui` is not compiled for ARM yet:
 ```
...
cert-manager   cert-manager-cainjector-6bc9d758b-cvf4x   1/1     Running            0               11m
cert-manager   cert-manager-6bbf595697-6m6zc             1/1     Running            0               11m
cert-manager   cert-manager-webhook-586d45d5ff-dpkxd     1/1     Running            0               11m
epinio         epinio-server-74654659f7-k8qjw            1/1     Running            0               9m4s
epinio         kubed-7c87544479-x54m5                    1/1     Running            0               9m3s
epinio         registry-8478dd7dd-28t69                  2/2     Running            0               9m3s
epinio         minio-0                                   1/1     Running            0               9m2s
epinio         epinio-ui-555dcdd58d-bmbpw                0/1     CrashLoopBackOff   6 (2m58s ago)   9m4s
```
```
pi@management:~ $ kubectl logs epinio-ui-555dcdd58d-bmbpw -n epinio
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by pgonin** [comment] 2022-05-19 13:06
If you build for arm64, could you also add s390 ?

**Comment by juadk** [comment] 2022-05-19 13:13
It will make sense to build it in the same arch as epinio-server:
```
epinio-darwin-arm64
epinio-darwin-x86_64
epinio-linux-arm64
epinio-linux-armv7
epinio-linux-s390x
epinio-linux-x86_64
epinio-windows-x86_64.zip
```

**Comment by juadk** [comment] 2022-06-13 15:46
Well, I've tried to compile epinio-ui for arm and s390x but I think that's more complicated.
I think Stratos (epinio-ui is a fork of Stratos) is not compatible with ARM yet.
https://github.com/epinio/ui-backend/pull/7
Unfortunately I don't think QA can do more regarding this ticket.

**Comment by richard-cox** [comment] 2022-06-13 15:56
The backend used by the standalone ui (`epinio/ui-backend`) is a highly modified fork of stratos. Everything else epinio ui related is `rancher/dashboard` (with certain flags to enable/disable functionality).

Unfortunately I don't know how golang / it's dependencies work on different architectures, someone epinio dev side might know though

**Comment by juadk** [comment] 2022-06-13 17:36
I tried to do the same as we have for epinio-server https://github.com/epinio/epinio/blob/main/.goreleaser.yml

**Comment by jimmykarily** [comment] 2022-08-31 13:02
The issue is easily reproducible is you go to the `src/jetstream` directory and you run:

```
GOOS=darwin GOARCH=arm64 go build 
```

**Comment by jimmykarily** [comment] 2022-08-31 14:00
Given a Dockerfile:

```
FROM ubuntu

# For GOARCH=arm :
#RUN apt update && apt install -y golang gcc-arm-linux-gnueabihf ca-certificates gcc-aarch64-linux-gnu
# For GOARCH=arm64:
RUN apt update && apt install -y golang ca-certificates gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

# For GOARCH=arm:
#ENV CC=arm-linux-gnueabihf-gcc
# For GOARCH=arm64:
ENV CC=aarch64-linux-gnu-gcc
ENV CXX=arm-linux-gnueabihf-g++

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /jetstream

CMD ["go", "build"]
```

built with:

```
docker build -t jetstream-arm .
```

This command works:

```
 docker run -it -v $PWD:/jetstream  jetstream-arm
```

I don't have an arm64 machine to try out the binary though.

**Comment by jimmykarily** [comment] 2022-09-01 07:15
Someone has this solution already implemented here: https://github.com/goreleaser/goreleaser-cross#examples

**Comment by thehejik** [comment] 2022-10-17 15:14
I was able reproduce the issue on `x86_64`:

**Comment by enrichman** [comment] 2022-11-09 11:34
[Trying to build also ](https://github.com/epinio/ui-backend/pull/10)

I've just added the linux architectures because we are not providing the docker images of Epinio for Mac or Windows. We are building only the binaries for the CLI, but I guess that we are not supporting them from the server side.

@pgonin I was trying to build it also for the `s390x` but I guess that is not supported. I will ask if they are planning to add the support, or if I'm missing something.

**Comment by thehejik** [comment] 2022-11-09 16:09
Another issue on aarch64 spotted https://github.com/epinio/epinio/issues/1847

**Comment by enrichman** [comment] 2022-11-10 08:52
The owner of the goreleaser-cross image opened an [issue](https://github.com/goreleaser/goreleaser-cross/issues/15) about the `s390x` architecture. 👍 

We are not able to build for the `armv7` arch because the `bci-micro` base image that we are using doesn't support it:

```
-> % docker manifest inspect registry.suse.com/bci/bci-micro | jq '.manifests[].platform'
{
  "architecture": "arm64",
  "os": "linux",
  "variant": "v8"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "linux"
}
```

**Comment by enrichman** [comment] 2022-11-14 14:43
Wrapping up the issue.

## Epinio / UI

The `epinio server` is built and released for the `amd64`, `arm64v8`, `armv7` and `s390x` architectures with [Goreleaser](https://github.com/epinio/epinio/blob/main/.goreleaser.yml).

The [UI backend](https://github.com/epinio/ui-backend) (`epinio-ui`) is now built for the `amd64` and `arm64v8` architectures. We are missing the `armv7` because the `registry.suse.com/bci/bci-micro` base image is missing this architecture.

```
-> % docker manifest inspect registry.suse.com/bci/bci-micro | jq '.manifests[].platform'
```
```json
{
  "architecture": "arm64",
  "os": "linux",
  "variant": "v8"
}
{
  "architecture": "ppc64le",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
{
  "architecture": "amd64",
  "os": "linux"
}
```

And we are missing the `s390x` because the `goreleaser-cross` image that we are using to cross-compile the UI is missing it.

Ref:
- https://github.com/goreleaser/goreleaser-cross/issues/15
  - https://github.com/goreleaser/goreleaser-cross/pull/16

## Building phase

Fixing the two previous issues we would have an Epinio that would be possible to release for all the architectures, but the build will still failing, because the Paketo Builder image is available only for the `amd64` architecture:
- https://github.com/epinio/epinio/issues/1850

**Comment by agracey** [comment] 2022-11-21 21:20
I think we can call this closed as it will work if you bring a custom builder image that works on ARM

**Comment by enrichman** [comment] 2023-02-09 14:43
With the latest PR we are going to support the `amd64`, `arm64` and `s390x` architectures.

```
-> % docker manifest inspect ghcr.io/epinio/epinio-ui:latest-next | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
{
  "architecture": "s390x",
  "os": "linux"
}
```

```
-> % docker manifest inspect ghcr.io/epinio/epinio-server:latest | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
{
  "architecture": "arm64",
  "os": "linux"
}
{
  "architecture": "arm",
  "os": "linux",
  "variant": "v7"
}
{
  "architecture": "s390x",
  "os": "linux"
}
```

As [already mentioned](https://github.com/epinio/epinio/issues/1473#issuecomment-1313863320) we are still missing the `armv7` beacuse of the `registry.suse.com/bci/bci-micro` base image.

Also the building stage will not work in other archs than the `amd64` because of the Paketo Builder image. It's still possible to use Epinio with docker images though, or provide a custom builder.

**Closed** 2023-02-13 11:24 UTC
Labels: kind/bug, kind/upstream
