### ISSUE TITLE
Very long loading-times for applications.

### ISSUE THREAD

**Issue by scures** [epinio/epinio#2087] opened 2023-02-14 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems that `Request URL:   api/v1/applications` takes a really long time to complete. With ~7 applications it takes from ~13 to 18 seconds for the request to complete. Also, under `https://localhost:8005/epinio/c/default/applications` seems that two requests are sent and I have the feeling the 2nd one is blocked until the first one finishes

![image](https://user-images.githubusercontent.com/88777903/218685547-ebb34e78-9a7d-4e13-a1e2-3cb1e1f72f01.png)

### Expected Behavior

We need to try and find out why the long response time (infra configuration, backend interaction...) and see why two request are trigger on the application view.

### Steps To Reproduce

1. https://localhost:8005/epinio/c/default/applications
2. Open the Network tab and you should see two requests triggered, you should see two /applications requests

### Environment

```markdown
- OS: 
- Architecture:
- Epinio Version: 1.6.2
- Cluster:
  - Provider: DO
  - Options:
  - Kubernetes Version: K3d with K3s v1.24.4+k3s1
```

**Comment by richard-cox** [comment] 2023-03-06 15:13
Linking https://github.com/epinio/ui/issues/195

**Comment by andreas-kupries** [comment] 2023-03-06 15:30
The diagram as shown only shows timing.
I am unable to see which requests are taking what time.
Is it the upload of the sources (`/import-git`, `/store`) ?
The staging ? (`/stage`)
The deployment of staging results ? (`/deploy`)

The last two in particular depend strongly on the performance of the underlying cluster
(starting and running the staging job, running a `helm install`)

The staging job is interesting is the build pack stuff looks for a previous image of the app as means of accelerating them (i.e. reusing layers, caching).

**Comment by richard-cox** [comment] 2023-03-06 16:24
@andreas-kupries This issue is solely about the performance of fetching all applications. The other [one](https://github.com/epinio/epinio/issues/2129) is for app creation

**Comment by andreas-kupries** [comment] 2023-03-06 16:33
Ah, sorry.

**Comment by mmartin24** [comment] 2023-03-06 16:36
BTW @scures and @richard-cox just confirmed the same using k3d... around 30s listing 10 apps

![image](https://user-images.githubusercontent.com/37271841/223173197-7f734505-6d8b-491d-b433-8b9739e8c979.png)

**Comment by mmartin24** [comment] 2023-03-07 08:56
FYI: I just noticed it takes 10 seconds to list the same 10 items in cli.

@andreas-kupries I also noticed autocomplete is tremendously slow in this case. Is this the same listing issue and should be fixed after the current ticket is fixed or should it have its own ticket?

https://user-images.githubusercontent.com/37271841/223372658-90a4e60d-cfe6-4d7c-9112-6509362d33d4.mov

**Comment by mmartin24** [comment] 2023-03-07 15:51
> FYI: I just noticed it takes 10 seconds to list the same 10 items in cli.
> 
> @andreas-kupries I also noticed autocomplete is tremendously slow in this case. Is this the same listing issue and should be fixed after the current ticket is fixed or should it have its own ticket?

Clarified offline it seems it should be solved with this issue.

@andreas-kupries I did actually check slowness times as application number grows and it seems quite linear (around 1 second per application approximately):

| Number of Apps      | Time to list (seconds) |
| ----------- | ----------- |
| 5      | 3-5        |
| 10  | 8-9         |
| 15  | 13-14         |
| 20  | 19-20         |

**Comment by andreas-kupries** [comment] 2023-03-07 16:05
I suspect that the linear part is the separate loading of various application data  stored in secrets, outside of the application resource(s). These are at least: environment assignments, scaling, bound configurations.

See https://github.com/epinio/epinio/blob/9c8da79b04acc1be43d678a77dfd051b1717711d/internal/application/application.go#L499

The starting point for `List` is a single call to get all the app resources from kube in one go.
This is then followed by the linear querying of the extended data.

To make this fast we should make a single List query for all the possible secrets and then handle the associations of secrets to apps in memory.

And the match endpoint can be made fast even without that change. Trivial even. We already have 2 list operations in the server, a `List` which loads and returns everything, and a `ListAppRefs` which essentially only loads the names. Match uses `List`, and should use `ListAppRefs`, because it does not need anything beyond the names.

**Closed** 2023-03-10 16:51 UTC
Labels: kind/bug, area/performance
