### ISSUE TITLE
[1.5.0] No default route created for an app deployed over WebUI

### ISSUE THREAD

**Issue by thehejik** [epinio/epinio#1890] opened 2022-11-25 10:59 UTC
**Describe the bug**
Epinio v1.5.0 installed over helm chart still uses outdated `ghcr.io/epinio/epinio-ui:v1.2.0-0.0.1` image. Seems the WebUI doesn't handle the routes changes introduced by https://github.com/epinio/epinio/issues/1799

As a result when an app is deployed over WebUI the default route is `none` and ingress for the app is not created.

Apps named `app` and `example` were created in WebUI and `check-cli` was created by epinio cli.
```
$ epinio apps list

🚢  Listing applications
Namespace: workspace

✔️  Epinio Applications:
|   NAME    |            CREATED            | STATUS |                   ROUTES                   | CONFIGURATIONS | STATUS DETAILS |
|-----------|-------------------------------|--------|--------------------------------------------|----------------|----------------|
| app       | 2022-11-25 09:35:14 +0000 UTC | 1/1    | <<none>>                                   |                |                |
| check-cli | 2022-11-25 09:56:16 +0000 UTC | 1/1    | check-cli.10.100.103.16.omg.howdoi.website |                |                |
| example   | 2022-11-25 09:25:00 +0000 UTC | 1/1    | <<none>>                                   |                |                |

**Comment by mmartin24** [comment] 2022-11-28 10:26
FTR. This was commented and fixed here: https://github.com/epinio/ui/issues/169 and it is being tested daily on UI regression tests with latest UI images. Since it is present on [rancher/dashboard(epinio-dev)](https://github.com/rancher/dashboard/tree/epinio-dev) after deploying latest ui image this issue should be fixed.

**Closed** 2022-12-01 10:08 UTC
Labels: bug
