### ISSUE TITLE
A second push doesn't seem to always trigger a restart after the build

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#262] opened 2021-04-08 13:44 UTC
I'm trying to build out a demo and running into the pod not always being restarted.

**Comment by andreas-kupries** [comment] 2021-04-08 13:53
This sounds similar to #141. Not enough details in here to be sure.

**Comment by agracey** [comment] 2021-04-08 13:54
Yeah, I somehow missed that issue when looking. Closing as dup

**Comment by jimmykarily** [comment] 2021-04-26 08:26
Maybe they are not the same issue (Troy changed the app from the Gitea web UI afaict). Let's open this and investigate.

**Comment by thardeck** [comment] 2021-04-30 07:00
As agracey stated in the bug which was originally marked as a duplicate, the issue is now that the ssl certificate does already exist which prevents an upgrade. The apps is recognized as existing though:
```
../../dist/epinio-linux-amd64 push sample-app
🚢 About to push an application with given name and sources into the specified organization
Name: sample-app
Sources: /epinio/assets/sample-app
Organization: test

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)

🚢 Application already exists. Updating.

Webhook already exists.

Preparing code ...
error pushing app: create local ssl certificate failed: quarkssecrets.quarks.cloudfoundry.org "test.sample-app.generate-certificate" already exists
```

**Comment by andreas-kupries** [comment] 2021-04-30 12:17
What would happen if we ignore this (specific) failure ?

**Comment by andreas-kupries** [comment] 2021-05-03 13:48
We (@thardeck and I) believe to know what is going on:

  - From earlier investigations we know that killing the app pod will cause the new app pod to show the modified application.

    That means that the entire pipeline, from event ligger, to tekton, etc. all runs, up to and including pushing a new image for the app to the registry.

  - Looking into the pipeline and deployment definitions we find that the image is specified based on the app name, and nothing else. Deployment (`client.go`):

    ```
      containers:
      - name: "{{ .AppName }}"
        image: "127.0.0.1:30500/apps/{{ .AppName }}"
    ```

    Tekton (`triggers.yaml`):

    ```
        - name: image
          resourceSpec:
            type: image
            params:
            - name: url
              value: registry.epinio-registry/apps/$(tt.params.appname)
    ```

  - This means than when tekton updates the deployment with the name of the new image, it is the same name as for the old image.
  - The deployment does not actually change.
  - There is no need to rotate the dependent pod.

And thus the behaviour we observe.

The solution we are working on "simply" adds the commit hash for the head of the `main` branch of the app to the image name. A push will change that part of the image name, thus the deployment changes, thus the pod should be rotated.

Working on this we ran into two additional issues, one solved, one not yet.

  - The `gitrevision` parameter of the `TriggerTemplate` (all in `triggers.yaml`) is set by the `TriggerBinding` using `body.head_commit.id` from the webhook's json. Unfortunately this is based on [GitHub webhook specs](https://www.openshift.com/blog/guide-to-openshift-pipelines-part-6-triggering-pipeline-execution-from-github). The existing setup only works because the `gitrevision` param has a default of `main`. For the [gitea webhook](https://docs.gitea.io/en-us/webhooks/) the proper field is `body.after`.
  - The unsolved issue is getting the head commit hash for branch `main` via the golang gitea client.
    We have confirmed, by looking directly at the `gitea` web interface, that tekton gets the proper head commit hash of `main`.
    What we have tried for `gitea` so far is not delivering that same information.

**Comment by andreas-kupries** [comment] 2021-05-03 13:50
Tried so far: `GetRepoBranch` and `GetSingleCommit` (https://gitea.com/gitea/go-sdk/src/branch/master/gitea)

**Comment by thardeck** [comment] 2021-05-05 08:30
Using the latest git commit is not possible because the deployment yaml is part of the latest git commit. Instead we us the previous commit to have an unique id to trigger the pod refresh.

**Comment by thardeck** [comment] 2021-05-05 08:32
We should create a follow up issue, that `epinio app push` does also on update wait until the update pod is up.

**Closed** 2021-05-05 13:25 UTC
Labels: bug, duplicate
