### ISSUE TITLE
Installation fails on MacOS

### ISSUE THREAD

**Issue by manno** [epinio/epinio#479] opened 2021-06-11 10:33 UTC
<details>
 <summary>Full Log</summary>

```
% ./epinio-darwin-amd64 install                                                                                                   
2021/06/11 12:07:34 InstallClient/Install "level"=1 "msg"="start"

🚢 Epinio installing...
2021/06/11 12:07:34 InstallClient/Install "level"=2 "msg"="process cli options"
2021/06/11 12:07:34 InstallClient/Install "level"=2 "msg"="fill defaults into options"
2021/06/11 12:07:34 InstallClient/Install "level"=2 "msg"="show option configuration"

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain:
  🧭  email_address: epinio@suse.com
  🧭  user: 6ca63b2809995443
  🧭  password: cf66b2a2baa2d4a2
2021/06/11 12:07:34 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="linkerd"

🚢 Deploying Linkerd...Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio865848608
Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio147322367

✔️  Linkerd deployed
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="traefik"

⚠️  Traefik Ingress already installed, skipping
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="ensure system-domain"
.
✔️  Created system_domain: 172.19.0.2.omg.howdoi.website
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="cert-manager"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="epinio"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="quarks"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="epinio-registry"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="tekton"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="service-catalog"
2021/06/11 12:08:55 InstallClient/Install "level"=2 "msg"="deploy"  "Deployment"="gitea"

🚢 Deploying CertManager...
🚢 Deploying ServiceCatalog...
🚢 Deploying Tekton...
🚢 Deploying Epinio...

🚢 Deploying Registry...🚢 Deploying Quarks...
🚢 Deploying Gitea...Executing  helm install cert-manager --namespace cert-manager /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio367137618 --set installCRDs=true
Executing  helm install service-catalog --namespace service-catalog /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio335794313
Executing  kubectl apply -n epinio --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio423284308
.I0611 12:08:56.527723   64645 request.go:655] Throttling request took 1.180060474s, request: POST:https://0.0.0.0:60505/api/v1/namespaces
Executing  helm install quarks --namespace quarks /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio085606819 --set image.tag=v1.0.760-lite --set global.monitoredID=quarks-secret
Executing  helm install gitea --values /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio322388646 --namespace gitea https://dl.gitea.io/charts/gitea-2.1.3.tgz
Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio170990541
...Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio359925448
.............Executing  kubectl apply -n epinio --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio235896634
...........Executing  kubectl apply -n tekton-staging --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio567012689
....................................I0611 12:09:12.454477   64645 request.go:655] Throttling request took 1.012209398s, request: GET:https://0.0.0.0:60505/api/v1/namespaces/service-catalog/pods/service-catalog-catalog-controller-manager-69f7d9d7d6-ql5xk
................................................
✔️  Quarks deployed
...Executing  helm install epinio-registry --set 'auth.htpasswd=ba0e8b330a0c3e6c:$2a$10$PAz3KXKEpHFzSYMq6xKiveQ9OSl/csmjQb/LwEYkLdbKTeceLQtve' --namespace epinio-registry /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio840202364
.............Executing  kubectl wait --for=condition=established --timeout=300s crd/clustertasks.tekton.dev
.........Executing  kubectl wait --for=condition=established --timeout=300s crd/conditions.tekton.dev
.Executing  kubectl wait --for=condition=established --timeout=300s crd/pipelineresources.tekton.dev
..Executing  kubectl wait --for=condition=established --timeout=300s crd/pipelineruns.tekton.dev
...Executing  kubectl wait --for=condition=established --timeout=300s crd/pipelines.tekton.dev
..Executing  kubectl wait --for=condition=established --timeout=300s crd/runs.tekton.dev
.Executing  kubectl wait --for=condition=established --timeout=300s crd/taskruns.tekton.dev
.Executing  kubectl wait --for=condition=established --timeout=300s crd/tasks.tekton.dev
...Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio387017131
......
🚢 retrying to apply tekton/pipeline.yaml
...........................Executing  kubectl apply --filename /var/folders/0j/zmrkp2sj2xjc_63fpfg4skv00000gn/T/epinio228156174
...
🚢 retrying to apply tekton/pipeline.yaml
......................panic: Deployment epinio failed with error: Creating Epinio server cert failed: creation of local ssl certificate failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": EOF


goroutine 65 [running]:
github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install.func1(0xc0003001b0, 0x2c53410, 0xc00036c500, 0x2c58fc0, 0xc000605b60, 0xc000605b54)
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:159 +0x217
created by github.com/epinio/epinio/internal/cli/clients.(*InstallClient).Install
	/home/runner/work/epinio/epinio/internal/cli/clients/install_client.go:156 +0xdc5
./epinio-darwin-amd64 install  8,01s user 3,94s system 9% cpu 2:03,70 total
```

</details>

`panic: Deployment epinio failed with error: Creating Epinio server cert failed: creation of local ssl certificate failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": EOF`

This looks similar to the  previous issue with MacOS/k3d/KinD: https://github.com/epinio/epinio/issues/404
Again, we have a webhook server, this time cert-manager, that's unable to answer requests.

**Comment by manno** [comment] 2021-06-14 08:51
There is also a report for:

> trying to install epinio 0.16 (today’s) on macOS RD (k3s 1.19), I get:
```
🚢 Deploying Linkerd...error installing Epinio: failed waiting Linkerd install job to complete: timed out waiting for the condition
```

**Comment by andreas-kupries** [comment] 2021-06-23 07:40
The linkerd timeout I have seen on Linux as well. That part does not seem to be OS specific.

**Comment by andreas-kupries** [comment] 2021-06-23 07:46
Linkerd issue put into new ticket #531

**Comment by andreas-kupries** [comment] 2021-06-23 07:47
If we go the same route as #404 we would have to retry some action. Do we know which action that is ?

**Comment by rohitsakala** [comment] 2021-06-23 09:35
I tried to install `epinio` from the `main` branch in my MacOS with K3d and docker desktop.

 I am not able to reproduce any of the issues mentioned. 

K3d : v4.4.4
MacOs: 11.3.1 Big Sur 
Docker Desktop: v3.3.3

@manno can you retry with the `main` branch ? Thanks. But, I am looking at certificate errors like `signed by unknown authority`. Will look into that now.

**Comment by rohitsakala** [comment] 2021-06-23 09:48
Seems like this commit [0] about retrying creating `epinio` certs is introduced after this issue if filed. So that must have solved this issue of epinio cert and webhook error.

[0] https://github.com/epinio/epinio/commit/7c99161e56f43a15f6efeb3f86c315383ca24de0#diff-892d335f47fd05c8157a81b96c028b3d6c1a88492ca015135d24fe86a1ede046

**Comment by rohitsakala** [comment] 2021-06-23 09:50
The `linkerd` bug has a separate issue now and it is not related to MacOS as @andreas-kupries mentioned. Closing this issue now.

**Closed by rohitsakala** 2021-06-23 09:50 UTC
Labels: bug
