### ISSUE TITLE
uninstall removes prior gitea instances with different namespaces

### ISSUE THREAD

**Issue by JamesTryand** [epinio/epinio#715] opened 2021-08-23 06:39 UTC
epinio installs gitea to the gitea namespace, however i had a previously existing gitea instance on the 'git' namespace. 

I came to remove epinio, but it removed my pods related to the gitea on the git instance in addition to those on the gitea namespace.

I'd rather not loose my repos.

**Comment by jimmykarily** [comment] 2021-08-23 12:17
Hi @JamesTryand , thank you for using Epinio and for taking the time to report this issue. I falied to reproduce the issue with these steps:

- I've installed Epinio
- I've installed a second instance of gitea using the same helm chart used by Epinio:

```
helm install gitea --namespace git https://dl.gitea.io/charts/gitea-2.1.3.tgz
```
- I removed Epinio: `epinio uninstall`
- The instance of gitea running in the `git` namespace is still there.

Also looking at the code, I see that we use a `--namespace` flag when deleting the gitea helm release: https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L94 so there is no way it can delete another release. I think the namespace only works for helm 3 though. @JamesTryand what helm version do you have installed? Did you install the second instance of Gitea using a helm chart or other method?

We also only delete the gitea namespace: https://github.com/epinio/epinio/blob/main/deployments/gitea.go#L105 . I can't reproduce this and I can't see how this can happen. Please let us know:

- how you installed the "manual" gitea instance
- what is the helm version you got installed next to epinio
- what pods got removed that shouldn't (their namespace and name)
- the epinio version you used (`epinio version` output)
- any errors you see on the cluster that may be relevant (crashlookbackoffs, kube events or other)

**Comment by JamesTryand** [comment] 2021-08-23 12:24
Thanks for getting back to me, and so quickly. I'll reproduce it again tonight, and make sure to include the various versions of things i use, with appropriate output.

**Comment by JamesTryand** [comment] 2021-08-24 00:30
Hi I too am now unable to replicate the issue. 

Just for the record i was using helm v3.6.3

i installed gitea via
```
kubectl create namespace git
helm repo add gitea https://dl.gitea.io/charts 
helm repo update
helm install my-gitea gitea/gitea --version 4.0.3 -n git
kubectl apply -f gitea-ingress.yaml
``` 
where gitea-ingres.yaml was a simple nginx ingress 

the services remained
```
git           service/gitea-ssh                  
git           service/gitea-http                 
git           service/gitea-postgresql-headless  
git           service/gitea-postgresql           
git           service/gitea-memcached            
```
but at the time there were no pods running in the 'git' namespace 

I ended up reinstalling my k3s instance but went from v1.21.3+k3s1 to v1.21.4+k3s1 since the previous version was causing issues with PVCs of installations of postgres 

Once again, thank you for your time I apologise for distracted you.

**Comment by jimmykarily** [comment] 2021-08-24 07:29
No worries! Thank you for testing it again. I'll close this issue now but if you encounter this again please re-open so we can investigate.

You feedback on Epinio is also very welcome. Join our Slack and stay in touch: https://github.com/epinio/epinio/#reach-us ;)

**Closed** 2021-08-24 07:29 UTC
Labels: bug, ux, installation
