### ISSUE TITLE
Getting epinio cli working behind identity aware proxy (like GCP/AWS's IAP)

### ISSUE THREAD

**Issue by gitricko** [epinio/epinio#2317] opened 2023-05-19 23:39 UTC
**Is your feature request related to a problem? Please describe.**
Cloud Providers are moving towards Identity Aware Proxies and it play very well with epinio's admin web ui as well as applications deploy inside epinio (with UI)

However, it is hard to protect epinio cli like epinio login and epinio push/logs/app-exec

Google's IAP provide us something like this for shell commands.
![signal-2023-05-19-062151_002](https://github.com/epinio/epinio/assets/18060558/680d7e26-1d41-4006-a5b9-6d90f1a045d7)

**Describe the solution you'd like**
Is there a way to integrate with epinio's dex or otherwise like:

```
epinio login --oidc https://epinio.internal.predev.xxxx.com \
   --headers "Authorization: Bearer $(gcloud auth print-identity-token ....)"
```

**Describe alternatives you've considered**
VPN developer machine into the network. Not ideal

**Comment by enrichman** [comment] 2023-06-19 13:43
Hi @gitricko, I was having a look at this issue and I'm not sure that the possibility to add custom headers is enough.

In your example you are logging in with `epinio login` and bypassing the IAP setting the `Authorization: Bearer XXX` header. What about any other further requests? Will the token generated with the OIDC login everything needed by the identity aware proxy, or not?

Basically after an oidc login we are going to pass the token with the same authorization header, so if you need to provide always a different token then Epinio will not be able to authenticate the request.

**Comment by enrichman** [comment] 2023-06-26 14:44
Since the #2395 was merged I'm going to close this. After the `1.9.0` release and some check we will see if we need to do something else.

**Closed by enrichman** 2023-06-26 14:44 UTC
Labels: kind/enhancement

**Comment by riqueps** [comment] 2023-08-10 13:02
Hi @enrichman
The Authorization bearer header worked, meaning epinio cli is able to reach epinio-server behind gcp iap, but unfortunately epinio cli is not being authenticated.

**CLI error with trace-level 255**
<img width="1628" alt="Screenshot 2023-08-10 at 09 44 27" src="https://github.com/epinio/epinio/assets/47371890/0e826cf8-d7ca-484d-8e7b-9f8ff364e5be">


**Server error**
<img width="1322" alt="Screenshot 2023-08-09 at 10 23 59" src="https://github.com/epinio/epinio/assets/47371890/08034380-e5c9-4e44-a23a-85ad47570fa1">

**To reproduce**
- Install epinio on gke
- Expose it through alb
- Enable IAP for epinio-server backend
- Create a service account with 'Service Account Token Creator' permission
- Grant access for the service account to epinio-server iap backend 
- Execute:
```
epinio login -u USER  -p PASSWORD https://epinio.URL \
   --header "Authorization: Bearer $(gcloud auth print-identity-token --include-email --audiences="OAUTH_CLIENT_ID" --impersonate-service-account=SERVICE_ACCOUNT)" --trace-level 255
```

**Comment by enrichman** [comment] 2023-08-11 11:58
Hi @riqueps, unfortunately it's a bit difficult to replicate the same infrastructure, but I did a quick search. Could you try to use the `Proxy-Authorization` header instead of the `Authorization`?

https://cloud.google.com/iap/docs/authentication-howto?hl=en#authenticating_from_proxy-authorization_header

**Comment by riqueps** [comment] 2023-08-11 14:32
You nailed @enrichman !!

**Login**
![image](https://github.com/epinio/epinio/assets/47371890/663e18e6-f288-4a44-b4ef-c8897bdf93f8)

**app list**
![image](https://github.com/epinio/epinio/assets/47371890/0f005e87-052f-4bb0-97cc-32e9fde1c648)

As you could see, '--header' should be passed for each request.
Is there a way to locally store the generated token for further requests?

**Comment by enrichman** [comment] 2023-08-11 22:32
Awesome! Unfortunately there is nothing natively available, you can probably work around it by aliasing the `epinio` command with the additional flag, or use a script/function that wraps the binary and adds the flag.

A more clear approach would be to add an environment variable for this flag (such as `EPINIO_HEADER`?) but I'm not completely sure on how to handle multiple values. A comma (`,`) is actually a valid character in a header value, and so it cannot be used to separate multiple headers. Multi-line header values were supported by [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt) but deprecated with the [RFC 7230](https://www.rfc-editor.org/rfc/rfc7230), so I think we could use this approach to add multiple headers with a single environment variable.

**Comment by riqueps** [comment] 2023-08-15 11:48
Hello @enrichman 
About your suggestion of create an aliasing for epinio command, I agree, but I during some extra testing I found an issue, it seems that the Proxy-Authorization Bearer is not being passed for further requests in the same epinio command, like on `epinio app push` or `epinio app delete`.

![image](https://github.com/epinio/epinio/assets/47371890/6afa9fae-7e41-41c8-a3ad-4dd4f768a20a)

![image](https://github.com/epinio/epinio/assets/47371890/b286c2d8-9850-407f-888e-3fc4f3516a02)

**Comment by enrichman** [comment] 2023-08-15 18:44
@riqueps can you confirm the behaviour increasing the TRACE_LEVEL? You will be able to check the headers sent. And if that's the case I would open an issue for this. :(

**Comment by riqueps** [comment] 2023-08-17 11:50
@enrichman , here are some print screens of 'epinio app push' command.
Looking at , I found 'Authorization : Bearer' instead of 'Proxy-Authorization: Bearer' (it's highlighted in red).

![image](https://github.com/epinio/epinio/assets/47371890/6ef46da9-ac76-4256-b2b7-a966d74ace57)

![image](https://github.com/epinio/epinio/assets/47371890/2db84ad9-2ac5-43a7-8dcf-2a4d93cd08c7)

![image](https://github.com/epinio/epinio/assets/47371890/8ee735d2-1fa9-435b-a23d-9ae918ef10a3)

![image](https://github.com/epinio/epinio/assets/47371890/84c10c8e-e3c2-416e-8e35-0d44226daf03)

**Comment by enrichman** [comment] 2023-08-31 15:19
Hi @riqueps, I tested it locally with the `v1.9.0` version and it works. I checked better your screenshots and it seems that the `Proxy-Authorization` header is present:

![261299196-2db84ad9-2ac5-43a7-8dcf-2a4d93cd08c7](https://github.com/epinio/epinio/assets/1763949/cbe122f5-a415-4a7a-a38f-cf774fd55b3a)

![261299284-84c10c8e-e3c2-416e-8e35-0d44226daf03](https://github.com/epinio/epinio/assets/1763949/e58a91a0-a496-4a12-8a6b-e7eecd7ee1b2)

**Comment by riqueps** [comment] 2023-09-05 13:23
I see.
But commands such, "epinio app push" and "epinio app delete" still not work for me.
In your tests were you able to push an app with --header flag?

**Comment by enrichman** [comment] 2023-09-05 13:47
@riqueps unfortunately I'm not able to reproduce your environment but I'm making assumption from your screenshots/logs.

If you have a look at the initial error (the very first [here](https://github.com/epinio/epinio/issues/2317#issuecomment-1673178802)) it was a 401, with missing credentials.

In the next tests you were able to pass the Proxy-Authentication header, that is working fine. Also from your logs it looks ok, the header is passed through the proxy, and the request is authenticated.

Now if you see the lates logs and error it's a `403`. That means that the request was authenticated (the header is passed and evaluated), but it's forbidden.

I don't have the full logs, so it's difficult to say, but it looks like the failed request is the one trying to upload the code and files to the server (I see the multipart and the boundary of the body). Maybe there is some configuration to fix or tweak to allow these kind or requests?

**Comment by riqueps** [comment] 2023-09-06 17:03
@enrichman , sorryyy my bad.
I didn't realize that waf was blocking epinio request, after I create some exception rules on waf, I was able to do app push and app delete.

thanks a lot for your help and patience 

The error *Failed to tail logs*, is related to [ALB RFC compliance](https://github.com/epinio/epinio/issues/2244), for this case we can ignore it.

![image](https://github.com/epinio/epinio/assets/47371890/10a7b425-c227-43cc-8f66-e9c937e81aad)

**Comment by riqueps** [comment] 2023-09-08 14:07
Hello @enrichman , about `epinio app logs`, at first I thought it was ALB RFC, but running it with trace-level 255, I see IAP response, `Invalid IAP credentials: empty token`.

Pls have a look at the output:

```
epinio app logs conda-header-test \
   --header "Proxy-Authorization: Bearer $(gcloud auth print-identity-token --include-email --audiences="AUDIENCE.apps.googleusercontent.com" --impersonate-service-account=SERVICE_ACCOUNT_NAME.iam.gserviceaccount.com)"  --trace-level 255
WARNING: This command is using service account impersonation. All API calls will be executed as [SERVICE_ACCOUNT_NAME.iam.gserviceaccount.com].
2023/09/08 10:47:20 Settings-0x140000d22d0: "level"=4 "msg"="Loading" "from"="/Users/henrique.souza/Library/Application Support/epinio/settings.yaml"
2023/09/08 10:47:20 Settings-0x140000d22d0: "level"=4 "msg"="Loaded" "value"="namespace=(henrique), user=(), pass=(), access_token=({eyJhbGciOiJSUzI1NiIsImtpZCI6IjNlMDU5NmRjMmNkZGM5MjY4OGQ1ZjI3ZWQxOWU3MzIxOTEzNzkxNWUifQ.eyJpc3MiOiJodHRwczovL2F1dGguaW50ZXJuYWwuc2FuZGJveGFudGhvcy5zZWN1cmVwbGF0Zm9ybWNyYWZ0c21lbi5jb20iLCJzdWIiOiJDaFV4TVRFNE16YzRNemcyTmpVek56Z3lOekV4T1RZU0JtZHZiMmRzWlEiLCJhdWQiOlsiZXBpbmlvLWFwaSIsImVwaW5pby1jbGkiXSwiZXhwIjoxNjk0MjA5MzYwLCJpYXQiOjE2OTQxODA1NjAsImF6cCI6ImVwaW5pby1jbGkiLCJhdF9oYXNoIjoiUXVnenNqMnZkQU5uYmUwU29CNzVYUSIsImVtYWlsIjoiaGVucmlxdWUuc291emFAY2hhc2UuaW8iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkhlbnJpcXVlIFNvdXphIiwiZmVkZXJhdGVkX2NsYWltcyI6eyJjb25uZWN0b3JfaWQiOiJnb29nbGUiLCJ1c2VyX2lkIjoiMTExODM3ODM4NjY1Mzc4MjcxMTk2In19.k4MuDwHHtQZKwwc0SdvINvOIwVLvdoCPbE9TevPJ9qMQ2xaQAoXcBy_qOF0uTfMxxiRIolqU_ZmEfpvb6nDCbHSDK8uYlUIdIRbs0L6ie0K3TJWjqBkPOzbWkvWiiht_sypCYUlYkXv_TRa01OOx1KW9PdVaMdv2CHyixGqAqTna_LAHaK1oyOzPYrNiJIQ8G_0N0uwy9T5sT266BY73KlIzmXeVfk3pZ2OMyNKpbUHotzftqIexuNNhrqen6VkUSCaP6-ChbYRDeWm8wyW6cH2y_4tOCMIdJeLsQLan4QGWC6fqu-_p3X5YJqQMsMqRaCa53WHSKEFZx7BF_kSAIw bearer Chl2azR0dW03Mm9pdG9oZ2hweWRnbDdua2ViEhlrMnludmdjbmdlazRwc2d0ZGxjYXlzYjZn 2023-09-08 18:42:39.095548 -0300 -03}), api=(https://epinio.DOMAIN.com), wss=(wss://epinio.DOMAIN.com), color=(true), appchart=(), @(/Users/henrique.souza/Library/Application Support/epinio/settings.yaml)"
2023/09/08 10:47:20 EpinioClient/NewEpinioClient: "level"=4 "msg"="Ingress API" "url"="https://epinio.DOMAIN.com"
2023/09/08 10:47:20 EpinioClient/NewEpinioClient: "level"=4 "msg"="Settings API" "url"="https://epinio.DOMAIN.com"
2023/09/08 10:47:20 EpinioClient/Apps: "level"=4 "msg"="start" "Namespace"="henrique" "Application"="conda-header-test"
🚢  Streaming application logs
Namespace: henrique
Application: conda-header-test
2023/09/08 10:47:20 EpinioClient/Apps: "level"=5 "msg"="application logs" "Namespace"="henrique" "Application"="conda-header-test"
2023/09/08 10:47:20 EpinioApiClient: "level"=5 "msg"="executing request" "method"="GET" "uri"="" "body"="" "header"={"Proxy-Authorization":["Bearer gMVWf0dfLMl0SwFGibd1V0FF5Ktn17qnQ6NAQ_YDGU7A3m35-n7b5iTW8UoQvcClp4npkeVCxRio2sd1kWVsfbbXuHb8Ya4ctIJD9QumxCAcVhtijQ_mk_cLzoC6S4VfwNw8pPaop9t8EFRZjzpCzOwHAQU0hjWZxrRIwCT56UEvm-U7OZZ8kVakDdqaV-kjd7T5h0Dwd2uRim0ypIvduDVc15rEz5L3ku9_8tGnhHq9_qMpfc1zSi8JIusgNWMLh0QSgPkSs_zabN88HchSfHB7DaX0TQ"],"Authorization":["Bearer OIwVLvdoCPbE9TevPJ9qMQ2xaQAoXcBy_qOF0uTfMxxiRIolqU_ZmEfpvb6nDCbHSDK8uYlUIdIRbs0L6ie0K3TJWjqBkPOzbWkvWiiht_sypCYUlYkXv_TRa01OOx1KW9PdVaMdv2CHyixGqAqTna_LAHaK1oyOzPYrNiJIQ8G_0N0uwy9T5sT266BY73KlIzmXeVfk3pZ2OMyNKpbUHotzftqIexuNNhrqen6VkUSCaP6-ChbYRDeWm8wyW6cH2y_4tOCMIdJeLsQLan4QGWC6fqu-_p3X5YJqQMsMqRaCa53WHSKEFZx7BF_kSAIw"]}
2023/09/08 10:47:21 EpinioApiClient: "level"=5 "msg"="response received" "status"=200 "body"="{\"token\":\"eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlcGluaW8tc2VydmVyIiwiZXtvNjOizmDwpf6BSLWugtRK-B-KRYHutCSwzTzWWgrFKyLrO_34PL86rROyVJfnkCj2ro0GJg\"}" "header"={"Date":["Fri, 08 Sep 2023 13:47:21 GMT"],"Content-Length":["490"],"Via":["1.1 google"],"Alt-Svc":["h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],"Content-Type":["application/json; charset=utf-8"],"Epinio-Version":["v1.9.0"]} "TLSServerName"="epinio.DOMAIN.com" "status"=200
2023/09/08 10:47:21 EpinioApiClient: "level"=5 "msg"="response decoded" "response"={"token":"eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlcGluaW8tc2VydmVyIiwiZpX759XDAkW6NoJdhTRtPzeO-M3PBRgpp5nhBF2eWmvNgyZD3sjk17Ff-ur9pGO-LI-7sKH4VA_tJe4wButvNjOizmDwpf6BSLWugtRK-B-KRYHutCSwzTzWWgrFKyLrO_34PL86rROyVJfnkCj2ro0GJg"}
2023/09/08 10:47:21 EpinioApiClient: "msg"="decoding json error" "error"="invalid character 'I' looking for beginning of value" "body"="Invalid IAP credentials: empty token"
2023/09/08 10:47:21 EpinioClient/Apps: "level"=4 "msg"="return" "Namespace"="henrique" "Application"="conda-header-test"
❌  error streaming application logs: parsing error response: invalid character 'I' looking for beginning of value


```

**Comment by riqueps** [comment] 2023-09-08 16:45
When IAP is disabled, I'm able to retrieve app logs.

![image](https://github.com/epinio/epinio/assets/47371890/f73b145e-11b3-4fa9-8486-12c1dad74d60)

**Comment by enrichman** [comment] 2023-09-08 16:49
Hm, ok, I guess the problem is then related to just the endpoints that are working on websockets, because they're working with a different authentication system, and maybe there's something wrong with it.

If my assumption is correct you should not be able to exec into the app as well.

**Comment by riqueps** [comment] 2023-09-08 16:54
For now I`m not able to test `epinio app exec` because of the ALB compliance with [RFC 72300](https://cloud.google.com/knowledge/kb/http-400-response-reported-by-external-http-s-load-balancer-000004693), as I mentioned before.

> @enrichman , sorryyy my bad. I didn't realize that waf was blocking epinio request, after I create some exception rules on waf, I was able to do app push and app delete.
> 
> thanks a lot for your help and patience
> 
> The error _Failed to tail logs_, is related to [ALB RFC compliance](https://github.com/epinio/epinio/issues/2244), for this case we can ignore it.
> 
> ![image](https://user-images.githubusercontent.com/47371890/266084788-10a7b425-c227-43cc-8f66-e9c937e81aad.png)

**Comment by riqueps** [comment] 2023-09-11 16:56
> Hm, ok, I guess the problem is then related to just the endpoints that are working on websockets, because they're working with a different authentication system, and maybe there's something wrong with it.
> 
> If my assumption is correct you should not be able to exec into the app as well.

New issue created to track the discussion/debug: https://github.com/epinio/epinio/issues/2560
