### ISSUE TITLE
Default installation shows wrong credentials in summary

### ISSUE THREAD

**Issue by svollath** [epinio/epinio#649] opened 2021-07-28 10:22 UTC
I installed Epinio (0.0.19) on Azure AKS with defaults, so just

`epinio install`

The output finally contained two value summaries, but also with different user credentials. Only the first credentials will work, the second set doesn't work:

```
 > ./epinio-0.0.19 install

🚢 Epinio installing...

Configuration...
  🧭  skip-traefik: false
  🧭  skip-linkerd: false
  🧭  system_domain: 
  🧭  email_address: epinio@suse.com
  🧭  user: 432890f5ebae48f0
  🧭  password: a9bf2ecd0b176912
  🧭  tls-issuer: epinio-ca
  🧭  use-internal-registry-node-port: true

🚢 Deploying Linkerd...
✔️  Linkerd deployed

🚢 Deploying Traefik Ingress......................
✔️  Traefik Ingress deployed
.
✔️  Using system_domain: 20.72.191.33.omg.howdoi.website

🚢 Deploying ServiceCatalog...
🚢 Deploying Epinio...
🚢 Deploying Tekton...
🚢 Deploying Kubed...
🚢 Deploying CertManager...
🚢 Deploying Registry...
🚢 Deploying Gitea...............................................................................................................................................................................
✔️  Kubed deployed
.................................................
🚢 retrying to create the epinio cert using cert-manager

🚢 Retrying creation of API cert via cert-manager (0/10)
................
✔️  CertManager deployed

✔️  Registry deployed
.........
✔️  Epinio deployed
....................................
✔️  ServiceCatalog deployed
........................................
✔️  Tekton deployed
.............................................
✔️  Gitea deployed
...............................................................................
✔️  Epinio installed.
System domain: 20.72.191.33.omg.howdoi.website
API User: be114e0d1ff0ae76
API Password: 0450dbc38ed2227c
Traefik Ingress info: [{"ip":"20.72.191.33"}]

🚢 Updating the stored credentials from the current cluster

✔️  Ok

🚢 Creating organization...
Name: workspace

✔️  Organization created.

🚢 Targeting organization...
Name: workspace

✔️  Organization targeted.
```

**Comment by rohitsakala** [comment] 2021-08-30 09:11
@svollath I am not able to reproduce this in the main branch. This issue should be fixed by https://github.com/epinio/epinio/issues/606. Please re open if you still see the issue.

**Closed by rohitsakala** 2021-08-30 09:11 UTC
Labels: bug
