### ISSUE TITLE
12factor sample fails to build

### ISSUE THREAD

**Issue by agracey** [epinio/epinio#410] opened 2021-05-20 00:11 UTC
I tried pushing https://github.com/scf-samples/12factor and got this error in the Create step of the Stage task:

```Paketo Bundle Install Buildpack 0.2.0
  Executing launch environment install process
    Running 'bundle config --global clean true'
    Running 'bundle config --global path /layers/paketo-buildpacks_bundle-install/launch-gems'
    Running 'bundle config --global without development:test'
    Running 'bundle config --global cache_path --parseable'
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/paketo-buildpacks/bundle-install.BundleInstallProcess.Execute(0x741760, 0xc0000518b0, 0x741780, 0xc00005a6c0, 0x741780, 0xc00005a6e0, 0x741780, 0xc00005a700, 0x741780, 0xc00005a720, ...)
	/tmp/dup-dest1041113364/bundle_install_process.go:195 +0x1825
github.com/paketo-buildpacks/bundle-install.Build.func1.2(0xc021841fd42de394, 0x60dcba)
	/tmp/dup-dest1041113364/build.go:146 +0x203
github.com/paketo-buildpacks/packit/chronos.Clock.Measure(0x6ffd38, 0xc000138b58, 0x741780, 0xc00005a6e0, 0x741780)
	/home/runner/go/pkg/mod/github.com/paketo-buildpacks/packit@v0.10.2/chronos/clock.go:21 +0x52
github.com/paketo-buildpacks/bundle-install.Build.func1(0xc00001c510, 0x20, 0xc00001c540, 0x1f, 0xc00001eee0, 0x5, 0xc00001a062, 0x36, 0x7ffd3bc08cca, 0x9, ...)
	/tmp/dup-dest1041113364/build.go:133 +0xb45
github.com/paketo-buildpacks/packit.Build(0xc000014240, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/paketo-buildpacks/packit@v0.10.2/build.go:140 +0x61e
github.com/paketo-buildpacks/packit.Run(0xc00000e0f0, 0xc000014240, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/paketo-buildpacks/packit@v0.10.2/run.go:31 +0x30a
main.main()
	/tmp/dup-dest1041113364/run/main.go:17 +0x347
ERROR: failed to build: exit status 2```

**Comment by andreas-kupries** [comment] 2021-05-20 07:27
The stack trace makes it seem an issue in the paketo buildpack(s) ?!

Should this be reported to the upstream paketo repos/project ?

Questions for us:
  - What release of the buildpacks do we use ?
  - Is it the latest ?
  - If not, why not ?

Dev question for us:
  - What is the process to replace the current paketo release in epinio with a different release, for testing.

**Comment by manno** [comment] 2021-05-20 13:09
That's interesting, we just use the latest!

https://github.com/epinio/epinio/blob/main/assets/embedded-files/tekton/pipeline.yaml#L51-L52

I verified the image ID in a fresh installation (buildpack-builder-* pod) and it maches the ID here: 
https://hub.docker.com/r/paketobuildpacks/builder/tags?page=1&ordering=last_updated

**Comment by andreas-kupries** [comment] 2021-05-20 13:39
Counter interesting: With us using whatever paketo buildpacks is latest (released) when running `epinio install`, it IMHO behooves us to show some kind of version information (maybe the image id ?) for this in our `epinio info`. To make sure what we are debugging the same thing as the user who reported some issue.

Another idea for the cause of the issue, it might be that the app itself is not properly matched to the expectations of paketo buildpacks. It does come from the old `scf-samples` repo. That is examples from before we had even `kubecf`.

**Comment by agracey** [comment] 2021-05-20 13:52
Yeah, it could be that there are version mismatches. I'll check the docs to make sure the expected tooling is there.

**Comment by agracey** [comment] 2021-05-20 14:24
Looks like https://github.com/bigcommerce/hello-world-app-ruby-sinatra has the same issue. I think the ruby buildpack is busted

**Comment by jimmykarily** [comment] 2021-05-25 08:18
We should investigate and make sure the problem is not on the Epinio side. If it's the buildpack, we should open an issue on their board or find an existing one for this problem (if there is one).

**Comment by agracey** [comment] 2021-05-25 13:44
I briefly looked at the buildpacks issue page and didn't see anything relevant

**Comment by thardeck** [comment] 2021-05-27 10:01
It really seems to be a paketo issue. If I remove the `Gemfile.lock` in the 12factor app I can push. The browser then says `Service Unavailable" but this seems to be another issue.

In case of https://github.com/bigcommerce/hello-world-app-ruby-sinatra removing the `Gemfile.lock` and removing the `ruby` and `group` entries from the `Gemfile`.

So the paketo bundle installation seems to be not fully compatible yet.

**Comment by thardeck** [comment] 2021-05-28 09:23
So the issue is that the apps are too old and the ruby/bundler versions are not supported, not much we can do and it is not really a bug in paketo.

The 12factor app can be fixed by providing a buildpack.yml (which is deprecated but of course the Gemfile can be adapted or a [`project.toml` ](https://github.com/paketo-buildpacks/bundler#bundler-configurations)can be used), because otherwise it uses Ruby 3 which does not work with the old bundler 1.

The supported versions are listed here: https://devcenter.heroku.com/articles/ruby-support#ruby-versions
```
mri:
      version: 2.6.7
```

**Comment by manno** [comment] 2021-05-28 09:50
I wouldn't say it's a bug in the buildpack :)

```
RUBY VERSION
   ruby 2.2.5p319

BUNDLED WITH
   1.16.4
```

The versions are just not supported, which it reports before it panicks, but that text was cut from the issue. 
Bundler buildpack falls back to 1.17, MRI buildpack uses Ruby 3.0 .
It tries to run an old bundler with Ruby 3 and bundler panicks.

So the user has to pick the right combination of Ruby and bundler that still works with their app's code and dependencies. Or update the app  to a supported version.
In this case we couldn't find a combination that would work, with the old dependencies. So the app has to be updated.

**Comment by jimmykarily** [comment] 2021-05-28 11:42
Seems both Epinio and buildpacks are fine. Closing this.

**Closed by jimmykarily** 2021-05-28 11:42 UTC
Labels: bug
