### ISSUE TITLE
Epinio "apps log" panics because channel is closed twice

### ISSUE THREAD

**Issue by manno** [epinio/epinio#1417] opened 2022-05-02 14:45 UTC
This came up during #1416 and blocks it. 
Tried to fix it with a mutex, but then apps log [unit](https://github.com/epinio/epinio/blob/main/acceptance/apps_test.go#L997) and [acceptance tests](https://github.com/epinio/epinio/blob/main/acceptance/apps_test.go#L997) would not terminate.

```
🕞  [test-799dfb8759-5p787] test [29-Apr-2022 14:20:58] NOTICE: ready to handle connections
2022/04/29 16:25:01 EpinioApiClient: "level"=4 "msg"="error reading message" "error"="websocket: close 1000 (normal)"
2022/04/29 16:25:01 EpinioClient/Apps: "level"=4 "msg"="return" "Namespace"="workspace" "Application"="test"
PASS
2022/04/29 16:25:01 EpinioApiClient: "level"=4 "msg"="error sending close message to websocket" "error"="websocket: close sent"
panic: close of closed channel
```

Channels are also garbage collected. However client code seems to rely on either `close()`. We have to make sure to only close the channel once: https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/client/apps.go#L378-L410

**Comment by andreas-kupries** [comment] 2022-05-02 14:57
Involves three goroutines, all client side

1. Websocket `RECEIVER` pushing messages into a []byte channel, loops.
2. A `CLOSER` waiting for the context to be done, and closing the websocket
3. Message `PRINTER` reading from the p[byte channel, loops.

Both 1. and 2. close the []byte channel on error ...
For 1 an error happens when the WS is closed (by the closer).

**Comment by andreas-kupries** [comment] 2022-05-02 15:13
Regular log handling and completion (push, app logs)...

|Main|RECEIVER|CLOSER|PRINTER|
|---|---|---|---|
|push||||
||messages|||
|||wait on context||
||||enter|
|||||
|CONTEXT cancellation||||
|||||
|||send ws close control message||
|||close ws||
||err - use of closed network connection|||
||msgchan closed|||
||||complete|
|||done||
|||||
|app logs||||
||messages|||
|||wait on context||
||||enter|
|||||
||err - err websocket: close 1000 (normal)|||
||msgchan closed|||
||||complete|

Note that in `app logs` the CLOSER is never triggered. The context is never properly done.

**Comment by andreas-kupries** [comment] 2022-05-03 07:50
The main difference between the two cases is that

  - `app logs` directly reads the logs from where they are stored, sends them over, and ends. Whereas
  - `push` uses watchers on the pods to get the logs as they are produced and does not know when they end.

In shorter, for `app logs` the server stops the websocket (which in turn ends the command), whereas for `push` the client does it (through the `CLOSER`) when the command ends.

**Comment by andreas-kupries** [comment] 2022-05-03 07:52
That implies that we should not need the `CLOSER` goroutine at all for `apps logs`.

**Comment by enrichman** [comment] 2022-05-03 07:58
Since the client are in _follow_ mode the websocket connection is kept open, since one of the two sides decide to close it.

If the client goes away (closing the browser) or if the server drops/close the connection for any reason (an error, or a restart).
That were the cases that I've seen during my tests with the UI.

**Comment by andreas-kupries** [comment] 2022-05-03 09:28
Confirmed using a cli compiled for coverage that `app logs` is slower, allowing the `CLOSER` goroutine to execute before the process terminates:

|app logs + cover|RECEIVER|CLOSER|PRINTER||
|---|---|---|---|---|
|start|||||
||messages||||
|||wait on context|||
||||enter||
||||||
||err - err websocket: close 1000 (normal)||||
||msgchan closed||||
||||complete||
|CONTEXT cancellation|||||
|||send ws close control message||NEW|
|||error websocket: close sent||NEW|
||| :boom: |||

Given that the `CLOSER` is apparently not required for this mode I will now attempt a fix which conditionally disables `CLOSER` on demand, and demands that for `app logs`. Instead of trying to force execution of only one `close()`.

**Closed** 2022-05-03 15:14 UTC
Labels: bug
