### ISSUE TITLE
Fixed 12factor app results in "Bad Gateway" statement

### ISSUE THREAD

**Issue by thardeck** [epinio/epinio#429] opened 2021-05-28 12:12 UTC
During debugging #410 I was able to fix the [12factor](https://github.com/scf-samples/12factor) app by specifying a Ruby version via the following `buildpack.yml` in the app directory:
```
mri:
    version: 2.6.7
```

With this fix the app can be pushed and the pod is up, but the result in the browser states "Bad Gateway". According to the logs the app should be fine.

**Comment by agracey** [comment] 2021-05-28 13:28
I wouldn't be surprised if this is a problem in the app as well.

**Comment by manno** [comment] 2021-05-28 14:45
Again shelling into the workload pod:

```
$ curl -v localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
```
So, IPv6 works.

```
$ curl 127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
```

IPv4 does not work, which is what our service points to.

**Comment by manno** [comment] 2021-05-28 15:10
This fixes the issue:

```
diff --git a/Procfile b/Procfile
index 5c636c6..ebf0f93 100644
--- a/Procfile
+++ b/Procfile
@@ -1 +1 @@
-web: bundle exec ruby web.rb -p $PORT
+web: bundle exec ruby web.rb -p $PORT -o 0.0.0.0
```

**Comment by rohitsakala** [comment] 2021-05-31 13:54
I cannot reproduce this bug on my environment. I am using minikube. Checking on k3d now.

**Comment by rohitsakala** [comment] 2021-05-31 15:17
I cannot reproduce it on k3d also. :/

**Comment by agracey** [comment] 2021-05-31 16:37
Hey, sorry. I think I might have fixed it in the app itself and pushed to scf-samples

**Comment by agracey** [comment] 2021-05-31 16:38
I did that late on Friday and didn’t think to update this ticket with that data :(

**Comment by rohitsakala** [comment] 2021-06-01 07:52
Okie. So, closing this now.

**Closed by rohitsakala** 2021-06-01 07:52 UTC
Labels: bug
