### ISSUE TITLE
V1.0.0: Port-forward not working

### ISSUE THREAD

**Issue by nunix** [epinio/epinio#1645] opened 2022-07-15 09:24 UTC
**Describe the bug**
The `epinio app port-forward` is not working with v1.0.0. It doesn't open the port and ends up with a generic error (see below)

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Install Epinio
2. Push the app: `epinio push -n app1`
3. Create a new port-forward: `epinio app port-forward app1 8088:8080`
4. Results in error: `❌  error port forwarding to application: error upgrading connection:`

**Expected behavior**
The port-forward should run successfully and the application would be accessible through the port opened.

**Logs**
Here are the logs from the command output with the trace level at 255

```
export TRACE_LEVEL=255

2022/07/15 10:35:21 Settings-0xc000914160: "level"=4 "msg"="Loading" "from"="/home/corsair/.config/epinio/settings.yaml"
2022/07/15 10:35:21 Settings-0xc000914160: "level"=4 "msg"="Loaded" "value"="namespace=(workspace), user=(admin), pass=(password), api=(https://epinio.127.0.0.1.sslip.io), wss=(wss://epinio.127.0.0.1.sslip.io), color=(true), appchart=(), @(/home/corsair/.config/epinio/settings.yaml)"
2022/07/15 10:35:21 EpinioClient/NewEpinioClient: "level"=4 "msg"="Ingress API" "url"="https://epinio.127.0.0.1.sslip.io"
2022/07/15 10:35:21 EpinioClient/NewEpinioClient: "level"=4 "msg"="Settings API" "url"="https://epinio.127.0.0.1.sslip.io"
2022/07/15 10:35:21 EpinioClient/Apps: "level"=4 "msg"="start" "Namespace"="workspace" "Application"="mysimpleapp"

  Executing port forwarding
Namespace: workspace
Application: mysimpleapp
2022/07/15 10:35:21 EpinioApiClient: "level"=4 "msg"="GET https://epinio.127.0.0.1.sslip.io/api/v1/authtoken"
2022/07/15 10:35:22 EpinioApiClient: "level"=5 "msg"="request finished" "method"="GET" "uri"="https://epinio.127.0.0.1.sslip.io/api/v1/authtoken" "body"=""
2022/07/15 10:35:22 EpinioApiClient: "level"=5 "msg"="response received" "status"=200 "header"={"Content-Length":["466"],"Content-Type":["application/json; charset=utf-8"],"Date":["Fri, 15 Jul 2022 08:35:21 GMT"],"Set-Cookie":["epinio-session=MTY1Nzg3NDEyMXxEdi1CQkFFQ180SUFBUkFCRUFBQV81UF9nZ0FCQm5OMGNtbHVad3dHQUFSMWMyVnlLMmRwZEdoMVlpNWpiMjB2WlhCcGJtbHZMMlZ3YVc1cGJ5OXBiblJsY201aGJDOWhkWFJvTGxWelpYTF9nd01CQVFSVmMyVnlBZi1FQUFFRkFRaFZjMlZ5Ym1GdFpRRU1BQUVJVUdGemMzZHZjbVFCREFBQkNVTnlaV0YwWldSQmRBSF9oZ0FCQkZKdmJHVUJEQUFCQ2s1aGJXVnpjR0ZqWlhNQl80Z0FBQUFRXzRVRkFRRUVWR2x0WlFIX2hnQUFBQmJfaHdJQkFRaGJYWE4wY21sdVp3SF9pQUFCREFBQUlfLUVJQUVGWVdSdGFXNENEd0VBQUFBTzJtSF9mQUFBQUFBQUFBRUZZV1J0YVc0QXyFYUWH8BhFTyJB3hu73n5ZpBwUHvvmuyqpnik7eXHUpw==; Expires=Sun, 17 Jul 2022 08:35:21 GMT; Max-Age=172800; HttpOnly; Secure"]} "TLSServerName"="epinio.127.0.0.1.sslip.io" "body"="{\"token\":\"eyJhbGciOiJSUzM4NCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJlcGluaW8tc2VydmVyIiwiZXhwIjoxNjU3ODc0MTUxLCJ1c2VyIjoiYWRtaW4ifQ.NICfXXm3Xi0FG-PG_nRaSc_6eXm1dElBMLu2c125Gd9K43TjKSauFE80f2lhxeVgpJyPMNXwsNhcZCP6qMdMsW5XHVoaLKWkPt-X_CcNUS6iJQdg68LjW19T7c3EPbrGNeX6hhVp8xyCQh-clxA3MmHQWEb6E_FtV034tH6hqzaXRVUe1L180xyAC2bjzfE7i9b_82NWI-4F73hmaXFDVjEaHHWiHav2RA7QTLvxCfPeLrkg2KJg9FC7dq3Flen3x4J1BUkRHzScUyl4yt0QAwir3m0CTZbKjuC_DJ7DUdZonUX55NmXbZPgkc9lEY_zhPf0zy4Y2RwvDb-DJOp6aQ\"}"
2022/07/15 10:35:22 EpinioClient/Apps: "level"=4 "msg"="return" "Namespace"="workspace" "Application"="mysimpleapp"

❌  error port forwarding to application: error upgrading connection:
```

To follow the server logs you can use:

`kubectl logs -n epinio -l app.kubernetes.io/name=epinio-server -c epinio-server -f`

```shell
Epinio version: v1.0.0

listening on localhost on port 8030
2022/07/15 08:02:16 http: proxy error: http2: invalid Upgrade request header: ["SPDY/3.1"]
```

**Cluster (please complete the following information):**
 - Provider: [e.g. K3D, minikube, KinD, AKS, EKS, GKE, RKE, ...]
 - Options: [e.g. number of nodes, storageclasses, loadbalancer if customised]
 - Kubernetes Version: [e.g. 1.20]

**Desktop/CLI (please complete the following information):**
 - OS: Linux OpenSUSE Tumbleweed
 - K8s cluster: Rancher Desktop 1.4.1
 - Epinio Version: 1.0.0
 - Epinio Install Options: N/A

**Additional context**
N/A

**Comment by andreas-kupries** [comment] 2022-07-27 07:55
The description unfortunately does not tell platform and cluster provider. This looks to be necessary information as a basic check in the dev environment failed to reproduce the issue.

My dev environment is linux, k3d v5.0.1-rc.1, k3s v1.21.5-k3s2, kube v1.20.11+k3s2.

Using the current main, i.e. commit 5d25c71ece2832aa83d964dac8bbd80cac04c378
  - cluster was started
  - epinio installed, then
  - `epinio push --name fox --path assets/sample-app/` followed by
  - `epinio app port-forward fox 8088:8080`

No error messages. A `curl http://localhost:8088/` worked ok as well. I.e. the main app page could be retrieved, as expected.

**Comment by andreas-kupries** [comment] 2022-07-27 08:04
Got the info that @mmartin24 managed to reproduce using Rancher Desktop on Mac.

**Comment by mmartin24** [comment] 2022-07-27 08:27
I managed to reproduce the issue on MAC. 

- Rancher Desktop version 1.4.1
- Kubernetes version: 1.24.2
- Container Runtime: dockerd

Steps as described in the description above:

1. Install Epinio
2. Go to repo `example-12factor`
3. Push the app: `epinio push -n app1` // The app should load correctly
4. Create a new port-forward: `epinio app port-forward app1 8088:8080`
5. Results in error: `❌ error port forwarding to application: error upgrading connection`

**Comment by nunix** [comment] 2022-07-27 09:57
@andreas-kupries concerning the platform+cluster, the information is at the end of the description (I agree, not standing out):

>Desktop/CLI (please complete the following information):
>OS: Linux OpenSUSE Tumbleweed
>K8s cluster: Rancher Desktop 1.4.1
>Epinio Version: 1.0.0
>Epinio Install Options: N/A

And I tried on Windows + Docker Desktop + Epinio extension and I got the same error.

**Comment by andreas-kupries** [comment] 2022-07-27 11:02
Oh, I see. The `please complete the following information` from that paragraph had me thinking that this was leftover from the issue template, like the preceding paragraph definitely is, and thus completely skipped over them both.

Lets make a table

|OS|Provider|Kubernetes|Result|Notes|
|---|---|---|---|---|
|Leap 15.3|k3d v5.0.1-rc.1|1.20.11| :heavy_check_mark: ||
|TumbleWeed ?|RD 1.4.1+?|?| :boom: | __"SPDY/3.1"__ |
|OSX ?|RD 1.4.1+dockerd|1.24.2| :boom: |

**Comment by andreas-kupries** [comment] 2022-07-27 12:12
Created ticket https://github.com/rancher-sandbox/rancher-desktop/issues/2639 for my troubles with RD.

**Comment by nunix** [comment] 2022-07-27 12:58
The versions I tested and it's failing are:
Rancher Desktop: v1.24.2+k3s2
Docker Desktop: v1.24.2

**Comment by andreas-kupries** [comment] 2022-07-27 13:01
@nunix gave me commands which extracted a usable kubeconfig from the RD, making the cluster accessible. Testing now ...

**Comment by andreas-kupries** [comment] 2022-07-28 07:59
The [RD 1.5 Release Notes](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.5.0) mention

> Due to upstream Kubernetes changes the automatic forwarding of NodePorts to the host no longer works for Kubernetes 1.22.10+, 1.23.7+, or any 1.24.1+ release (this also affects all previous Rancher Desktop releases).

as a known issue.

**Comment by mmartin24** [comment] 2022-07-28 08:57
In regards to [this](https://github.com/epinio/epinio/issues/1645#issuecomment-1197799695) new info, I tried to test it downgrading the Kubernetes version to `1,21,14` using the same Rancher Desktop as yesterday (1.4.1) and I got this error when I tried to push the app:

```
➜  example-12factor git:(main) epinio push -n app-k8s-v-12114

🚢  About to push an application with the given setup
Manifest: <<Defaults>>
Name: app-k8s-v-12114
Source Origin: /Users/mamartin/epinio-repos/example-12factor
AppChart:
Target Namespace: workspace

⚠️  Hit Enter to continue or Ctrl+C to abort (deployment will continue automatically in 5 seconds)

Create the application resource ...
2022/07/28 10:48:40 EpinioApiClient: "msg"="request failed" "error"="Post \"https://epinio.127.0.0.1.sslip.io/api/v1/namespaces/workspace/applications\": x509: certificate is valid for 750b081f9f4cea7ff364ca2476085784.2a0e58a315508ff99094d15f559b3f2f.traefik.default, not epinio.127.0.0.1.sslip.io"

❌  error pushing app to server: making the request: Post "https://epinio.127.0.0.1.sslip.io/api/v1/namespaces/workspace/applications": x509: certificate is valid for 750b081f9f4cea7ff364ca2476085784.2a0e58a315508ff99094d15f559b3f2f.traefik.default, not epinio.127.0.0.1.sslip.io
```
I am not sure what is happening. Will continue investigating

**Comment by andreas-kupries** [comment] 2022-07-28 08:59
Incorrect system domain ?

**Comment by mmartin24** [comment] 2022-07-28 09:03
I always understood it is automatically handled by RD.
Checking k9s I see `lima-rancher-desktop` node running:


![Image](https://user-images.githubusercontent.com/37271841/181466535-9eb2d152-0253-4e2f-b031-763962097534.png)

I will keep looking

**Comment by mmartin24** [comment] 2022-07-28 09:57
I had to do a factory reset and reinstall certificates and application.
For some reason I have to add the `--skip-ssl-verification` flag.
The installation takes places succesfully:


![Image](https://user-images.githubusercontent.com/37271841/181477531-1a4904cf-929b-4ed7-ac57-1d4946c0258a.png)

When I execute the port-forwarding it does not fail (which confirms) that seems related to the version, but it never ends executing it and seems to be in a frozen state:

```
➜  example-12factor git:(main) epinio app port-forward --skip-ssl-verification app-k8sv-12114 8088:8080

🚢  Executing port forwarding
Namespace: workspace
Application: app-k8sv-12114
Forwarding from 127.0.0.1:8088 -> 8080
Forwarding from [::1]:8088 -> 8080

```
I can try to install other versions and see if it works there, but I wonder if this is necessary, since the main thing is that the problem is related with Kubernetes versioning.

@andreas-kupries  or @nunix what do you think?

**Comment by andreas-kupries** [comment] 2022-07-28 10:40
The port forwarding command does not end by design. The moment you end that command the port forwarding ends.
In other words, that is correct behaviour, as far as I know - @enrichman 

Agreed, to me this looks to be a kubernetes/RD issue.

**Comment by mmartin24** [comment] 2022-07-28 11:33
Actually, after a nice conversation with @nunix we saw that the port redirection worked.
Then is I had to use `http` instead of `https` since the `--skip-ssl-verification` flag was added
Checked on version `1.20.15`

<img width="541" alt="image" src="https://user-images.githubusercontent.com/37271841/181495249-0a693bbe-1bc1-4407-8555-e5361b60418a.png">

**Comment by jimmykarily** [comment] 2022-08-01 08:21
This is a bug in Rancher Desktop. Closing this.

**Closed by jimmykarily** 2022-08-01 08:21 UTC
Labels: bug
