### ISSUE TITLE
epinio cli should check server version

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#1395] opened 2022-04-27 12:33 UTC
Until we have a more stable API, we should add a check in the cli that it's matching the server version (for now exact match). If they don't match, a warning should be printed and exit the command with an error.

In the future, we can be more flexible with versions and allow small differences between the client and the server.

**Comment by enrichman** [comment] 2022-10-10 08:52
Duplicate of https://github.com/epinio/epinio/issues/1153

**Closed by enrichman** 2022-10-10 08:52 UTC
