### ISSUE TITLE
Buildpack node engine memory available logging error

### ISSUE THREAD

**Issue by malcolmlewis** [epinio/epinio#575] opened 2021-07-02 13:41 UTC
Hi
During the SUSE & Rancher Accelerate Dev Workflows challenges this week, I see an error (non-fatal) in the epinio app logs. 

Host OS: openSUSE Tumbleweed x86_64
Example used: https://media2-production.mightynetworks.com/asset/25756223/3-use-service.pdf

Errors observed when running `epinio app logs shoppinglist`

```
🚢 Streaming application logs
Organization: shoppinglist
Application: shoppinglist
🕞  [shoppinglist-748d6757bd-fkndt] shoppinglist cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory 
🕞  [shoppinglist-748d6757bd-fkndt] shoppinglist /layers/paketo-buildpacks_node-engine/node/profile.d/0_memory_available.sh: line 3: / ( 1024 * 1024 ) : syntax error: operand expected (error token is "/ ( 1024 * 1024 ) ")
```

**Comment by andreas-kupries** [comment] 2021-07-02 14:18
The logs you are seeing and reporting are something coming directly out of the paketo buildpack(s) as they work on staging the application.

Epinio simply passes this information through to the user. It has no influence on the interaction of application sources and respective buildpacks, and any warnings and errors coming out that interaction.

I see this better reported to the maintainers of paketo and of the application itself (I am unable to tell if the cause for these warnings would be in the application not matching paketo's expectations, or in paketo wrongly stumbling on something in the application sources it should be able to handle.

**Comment by andreas-kupries** [comment] 2021-07-02 14:19
The application seems to be https://github.com/SUSE-Rancher-Community/example-express-redis, if I read the pdf correctly.
The maintainer might be @timirnich

**Comment by agracey** [comment] 2021-09-16 00:15
@malcolmlewis Is this still an issue?

**Comment by jimmykarily** [comment] 2021-10-11 08:42
Epinio is using the latest full builder image so if this is a buildpack issue, it may have already been fixed. Since there was no update on this issue, I will close it. @malcolmlewis feel free to re-open it if the problem is still there. Please add more information if that's the case.

**Closed by jimmykarily** 2021-10-11 08:42 UTC
Labels: bug
