### ISSUE TITLE
App exec endpoint does not work with letsencrypt

### ISSUE THREAD

**Issue by juadk** [epinio/epinio#1396] opened 2022-04-27 15:02 UTC
Dimitris pushed an app with letsencrypt and he was unable to get a shell from the pod.

```
~/workspace/epinio/helm-charts/chart/epinio (bump-epinio-ui)*$ epinio app exec heroku

🚢  Executing a shell
Namespace: workspace
Application: heroku

❌  error getting a shell to application:
``` 

Logs from the server:
`2022/04/27 14:47:22 http: proxy error: http2: invalid Upgrade request header: ["SPDY/3.1"] `

https://community.traefik.io/t/ingress-doesnt-work-with-connection-upgrade/889

Epinio helm chart version: `0.9.1 `

**Comment by jimmykarily** [comment] 2022-04-27 15:08
I also tried `epinio-ca` and `selfsigned-issuer`, they all fail with the same error. The cluster I used is in DigitalOcean, maybe that's relevant.

**Comment by jimmykarily** [comment] 2022-04-27 15:22
https://github.com/pomerium/pomerium/issues/2126

**Comment by jimmykarily** [comment] 2022-05-12 12:17
This is reproducible on minikube too. Simply following the instructions here: https://docs.epinio.io/howtos/install_epinio_on_minikube

**Comment by jimmykarily** [comment] 2022-05-12 13:11
Traefik seems to have merged  a fix in Traefik 2.1 for this:

- Issue: https://github.com/traefik/traefik/issues/6527
- PR: https://github.com/traefik/traefik/pull/6554


Still, I'm using traefik 2.5.1 and I still get this issue.

**Comment by jimmykarily** [comment] 2022-05-16 12:51
I compared the request headers between k3d (where exec is working) and minikube (where it fails). They are similar except for the case:

k3d:
```
req.Header = map[Accept-Encoding:[gzip] Connection:[Upgrade] Upgrade:[spdy/3.1] User-Agent:[Go-http-client/1.1] X-Forwarded-For:[10.42.0.1] X-Forwarded-Host:[epinio.172.18.0.4.omg.howdoi.website] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[traefik-6f9cbd9bd4-flc5p] X-Real-Ip:[10.42.0.1] X-Stream-Protocol-Version:[v4.channel.k8s.io v3.channel.k8s.io v2.channel.k8s.io channel.k8s.io]]
```

minikube:
```
req.Header = map[Accept-Encoding:[gzip] Connection:[Upgrade] Upgrade:[SPDY/3.1] User-Agent:[Go-http-client/1.1] X-Forwarded-For:[172.17.0.1] X-Forwarded-Host:[epinio.192.168.49.100.omg.howdoi.website] X-Forwarded-Port:[443] X-Forwarded-Proto:[https] X-Forwarded-Server:[traefik-875c68859-48rzw] X-Real-Ip:[172.17.0.1] X-Stream-Protocol-Version:[v4.channel.k8s.io v3.channel.k8s.io v2.channel.k8s.io channel.k8s.io]]
```
I even replaced the upper case `SPDY` with `spdy` in the proxy to check but it still fails. I start thinking that maybe it's not an issue with traefik but rather with Kubernetes version. I see some changes regarding spdy in recent versions: https://github.com/kubernetes/kubernetes/pull/108531

I will now k3d with version 1.22.2 which is the one failing in minikube. This should have been the first step...

**Comment by jimmykarily** [comment] 2022-05-16 14:02
Newer k3s/k3d comes with traefik v2. There doesn't seem to be a traefik helm chart for traefik v1 so I'll try something else instead. I'll try the working kubernetes (1.19) with traefik v2 to see if it works. If yes then it's the kuberentes version. If not then it's (at least) the traefik version.

**Comment by jimmykarily** [comment] 2022-05-16 14:16
k3d with kubernetes v1.20.11+k3s2 (k3s image: rancher/k3s:v1.20.11-k3s2) and Traefik helm chart `10.19.5` running traefik `2.6.6`  works. So it's not traefik that breaks it. Something must have changed in newer Kubernetes versions.

**Comment by jimmykarily** [comment] 2022-05-17 12:05
I run these on epinio main#
- `minikube start --kubernetes-version=v1.23.1 --container-runtime=containerd --driver=docker`
- `minikube addons enable metallb`
- `minikube ip` -> `172.17.0.2`
- `minikube addons configure metallb` (range from `172.17.0.100` to `172.17.0.130`) 
- `kubectl create namespace traefik`
- `helm install traefik --namespace traefik "https://helm.traefik.io/traefik/traefik-10.19.5.tgz" --set globalArguments=''--set-string ports.web.redirectTo=websecure --set-string ingressClass.enabled=true`
- `make install-cert-manager`
- `helm install -n epinio --create-namespace epinio helm-charts/chart/epinio --set global.domain=172.17.0.100.omg.howdoi.website` (where `172.17.0.100` is the ip address of the traefik svc)
- `epinio settings update`
- `epinio push -n sample --container-image-url splatform/sample-app`
- `epinio app exec sample`

boom! it doesn't work: 

```
❌  error getting a shell to application:
```

and on the server side:
```
2022/05/17 12:04:47 http: proxy error: http2: invalid Upgrade request header: ["SPDY/3.1"]                                                                                                                       
```

**Comment by jimmykarily** [comment] 2022-05-17 12:36
btw, `epinio app logs` works in minikube. This is also a websockets endpoint with an upgrade request and spdy protocol used. We handle this differently here though: https://github.com/epinio/epinio/blob/660ca3a6dc3a59cba2560cf207275d41281f170a/pkg/api/core/v1/client/apps.go#L354

(compare to: https://github.com/epinio/epinio/blob/660ca3a6dc3a59cba2560cf207275d41281f170a/pkg/api/core/v1/client/apps.go#L488)

**Comment by jimmykarily** [comment] 2022-05-17 14:54
I followed the steps here and added some more flags to the `minikube start` command in order to enable the audit policy: https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/

My policy looks like this: 

```
~/workspace/epinio/epinio (main)*$ cat ~/.minikube/files/etc/ssl/certs/audit-policy.yaml 
# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: RequestResponse
```

and my minikube command: 

```
minikube start   --extra-config=apiserver.audit-policy-file=/etc/ssl/certs/audit-policy.yaml --extra-config=apiserver.audit-log-path=- --kubernetes-version=v1.23.1 --container-runtime=containerd --driver=docker
```

**Comment by jimmykarily** [comment] 2022-05-18 06:53
ok some progress made. The original error comes from here: https://github.com/golang/net/blob/master/http2/transport.go#L1083-L1085

and finding references it seems that the http2 RoundTripper was used: https://github.com/golang/net/blob/183a9ca12b87817e0ced91cdd139606cbb193ef2/http2/transport.go#L1135

The question is why was an http2 transport configured in the first place? Those methods act on a request object, nothing has left the epinio server yet, there is no reponse. Our [ReverseProxy](https://github.com/epinio/epinio/blob/660ca3a6dc3a59cba2560cf207275d41281f170a/internal/api/v1/application/exec.go#L105) is using a client as it is constructed using the available RestConfig. So it must be something in the RestConfig that forces http2. Printing the `cluster.RestConfig` [somewhere here](https://github.com/epinio/epinio/blob/660ca3a6dc3a59cba2560cf207275d41281f170a/internal/api/v1/application/exec.go#L81), shows that it has: 

```
NextProtos:[] string(nil)
```
which probably makes it use defaults? The following patch fixes the issue in minikube:

```
diff --git a/helpers/kubernetes/cluster.go b/helpers/kubernetes/cluster.go
index 6cda88cf..58a1fd7f 100644
--- a/helpers/kubernetes/cluster.go
+++ b/helpers/kubernetes/cluster.go
@@ -94,6 +94,8 @@ func GetCluster(ctx context.Context) (*Cluster, error) {
        config.WarningHandler = restclient.NoWarnings{}
 
        c.RestConfig = restConfig
+       // NOTE: Navigate to this attribute for more docs on possible values
+       config.NextProtos = []string{"http/1.1"}
        clientset, err := kubernetes.NewForConfig(config)
        if err != nil {
                return nil, err
```
though we probably don't want to disable http2 globally. We will to refactor things a bit to allow the creation of a client that forces http1.1 when needed.

I will compare with k3d to see if the restconfig looks different there (we are using in-cluster config).

**Comment by jimmykarily** [comment] 2022-05-18 11:41
I couldn't figure out what causes the client to take the `http2` route in the case of minikube. I'm assuming some difference in the in-cluster config between the 2 clusters but I could not verify that. In any case, I create [a PR](https://github.com/epinio/epinio/pull/1464) that uses an http/1.1 client for the proxy. This fixes the issue.

Given we don't know how to reproduce the bug consistently, I can't write a test for it.

**Closed** 2022-05-20 07:39 UTC
Labels: bug
