### ISSUE TITLE
AKS-CI is failing

### ISSUE THREAD

**Issue by ldevulder** [epinio/epinio#1101] opened 2022-01-10 10:08 UTC
The AKS-CI test is failing during app deployment with this error:
```
Deploying application ...
  2022/01/09 03:47:00 EpinioApiClient "msg"="response is not StatusOK" "error"="Internal Server Error: invalid character 'a' in string escape code" "status"=500 
  error pushing app to server: can't deploy app: Internal Server Error: invalid character 'a' in string escape code
```

For example see this test: https://github.com/epinio/epinio/runs/4751235189?check_suite_focus=true

I was not able to reproduce the issue with manual test on Linux client as well as CI installation test running on a linux client. The CI test runs on a Windows client, maybe something is not exported correctly by Epinio which could explain this error?

**Comment by manno** [comment] 2022-01-17 09:21
The Epinio CLI complains about a 500 reply from the server. The json error parser fails, because the response is not JSON. It's likely the error message did not originate from the Epinio API server.

This might be a temporary issue, which could be fixed by retrying API requests: https://github.com/epinio/epinio/issues/807

**Comment by ldevulder** [comment] 2022-01-18 16:23
During my Rancher Desktop tests on Windows 10, I was able to reproduce the same kind of issue:
```
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create ===> EXPORTING
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'paketo-buildpacks/ca-certificates:helper'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'paketo-buildpacks/httpd:httpd'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'paketo-buildpacks/php-dist:php'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'paketo-buildpacks/php-web:php-web'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding 1/1 app layer(s)
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'launcher'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'config'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding layer 'process-types'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding label 'io.buildpacks.lifecycle.metadata'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding label 'io.buildpacks.build.metadata'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding label 'io.buildpacks.project.metadata'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Setting default process type 'web'
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Saving epinio-registry.172.22.189.158.omg.howdoi.website/apps/workspace-sample-app:efeda7c398a918db...
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create *** Images (sha256:c357ebf50d5300a24bcf95683cf7f566690a804420decccc9dcb63512f805c72):
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create       epinio-registry.172.22.189.158.omg.howdoi.website/apps/workspace-sample-app:efeda7c398a918db
🕞  [efeda7c398a918db-stage-bbtkn-pod-p6v8g] step-create Adding cache layer 'paketo-buildpacks/php-dist:php'

Deploying application ...
2022/01/18 16:48:43 EpinioApiClient "msg"="response is not StatusOK" "error"="Internal Server Error: invalid character 'U' in string escape code" "status"=500
error pushing app to server: can't deploy app: Internal Server Error: invalid character 'U' in string escape code
```

@jimmykarily do you think that @manno idea could solve the issue?

**Comment by jimmykarily** [comment] 2022-01-19 06:34
@ldevulder it could but I can't tell because I don't know what the issue is :). I think we should try to unmarshal the response as JSON but if that fails, instead of printing the unmarshaling error, we should print the original one with something like:

```
We couldn't unmarshal the erro as JSON, the original response was: blah blah
```

This way we won't hide the actual error. We can decide about retrying after we find what the problem is

**Comment by manno** [comment] 2022-01-20 10:30
@ldevulder we can't tell where the error comes from. You could be talking to any server (DNS problem), the loadbalancer (ingress/tls problem) or the Epinio API server. 

The problem with [retrying](https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/client/apps.go#L253-L275) is, that in our client implementation the '[curl](https://github.com/epinio/epinio/blob/main/pkg/api/core/v1/client/http.go)' (it's not curl) helper hides some response fields. Every client method, has different conditions on what responses are considered to be ok and not a hard failure.

**Comment by manno** [comment] 2022-01-21 10:36
Can you try with a higher trace level?

Since the error is reported client-side, you only need to `export TRACE_LEVEL=255`. You could also use `--trace-level`.

See https://github.com/epinio/epinio/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

If you want to see more logging on the server side, you either have to deploy with a higher trace level, or you edit (k9s, kubectl edit, ...) the epinio server deployment and change the TRACE_LEVEL env var.

**Comment by ldevulder** [comment] 2022-01-21 12:46
Here the logs after trying to push an app, hope it will help!

[epinio-dev-push.log](https://github.com/epinio/epinio/files/7913662/epinio-dev-push.log)

**Comment by manno** [comment] 2022-01-21 13:38
It looks to me like the client reached the right server. Can't be sure because the body is not logged by the current Epinio version, but the header `"Access-Control-Allow-Origin":["*"]` looks like the one we set?

**Comment by enrichman** [comment] 2022-01-21 15:36
Having a look at the logs I've seen that is originated from here

https://github.com/epinio/epinio/blob/9b66f630027d0019ca34d65eb06b7a7cf4f517df/internal/api/v1/application/deploy.go#L170-L174

and the problem is within the SetOrigin function, that is creating the JSON body "manually"

https://github.com/epinio/epinio/blob/9b66f630027d0019ca34d65eb06b7a7cf4f517df/internal/application/origin.go#L107-L140

On Windows the path are defined with a backslash, like `C:\Documents\myapp` and this is causing an issue on the unmarshal of the body from the Kubernetes api.

I did a test that is failing in the same way, so I'm pretty confident that's the problem.
I'll try a fix and let you know.

**Comment by andreas-kupries** [comment] 2022-01-21 15:42
Oh ... Blame me then, that is my code.

**Comment by andreas-kupries** [comment] 2022-01-21 15:45
And https://stackoverflow.com/questions/9371031/how-do-i-create-crossplatform-file-paths-in-go might be helpful.

**Closed** 2022-01-26 16:41 UTC
Labels: bug, QA
