### ISSUE TITLE
`epinio app manifest` should update routes

### ISSUE THREAD

**Issue by jimmykarily** [epinio/epinio#952] opened 2021-11-03 08:35 UTC
This is a fix for this comment: https://github.com/epinio/epinio/pull/942#issuecomment-958733119

Let's wait until #594 is done to avoid conflicts and fix it only once.

**Comment by andreas-kupries** [comment] 2021-11-03 13:41
The domain configuration is, AFAICT the `routes` field of `ApplicationUpdateRequest`. Should be mapped to the yaml key `configuration.routes`.

**Comment by andreas-kupries** [comment] 2021-11-03 14:28
Confirmed missing. Ok,time to investigate, because I saw the yaml tags on the structure, would have expected it to be marshaled.

**Comment by andreas-kupries** [comment] 2021-11-03 14:35
Ah. Data not yet returned by the server.

**Comment by andreas-kupries** [comment] 2021-11-03 14:43
Needs to be fixed in `application/application.go`, `fetch()`.

Yep. Use `ListRoutes()`. from the `ingresses.go` sibling.

**Comment by andreas-kupries** [comment] 2021-11-03 14:49
No. `ListRoutes` is for the active routes of a running app. Need something new for the routes of an app at rest.
... Lets look at #954 if that already got something for this.

**Comment by andreas-kupries** [comment] 2021-11-03 14:54
No.

**Closed** 2021-11-08 10:24 UTC
Labels: bug
