### ISSUE TITLE
Services returned by list differ from those when fetched directly

### ISSUE THREAD

**Issue by richard-cox** [epinio/epinio#981] opened 2021-11-12 13:38 UTC
**Describe the bug**
The response when fetching services by list is different from that when directly fetching a service. Ideally they should both match and return the same data (including the key-value service data)

This does currently cause an issue in the UI when refreshing on service detail page (we fetch the specific service and it doesn't contain the required data to show the service info) - https://github.com/epinio/ui/issues/45. It also means the user cannot edit their service's key-value pairs (they're not present from the list https://github.com/epinio/ui/issues/46)

**To Reproduce**
Fetch service lists via `/api/v1/namespaces/<ns>/services` or `/api/v1/services` and service is
```
{"meta":{"name":"aaaaaa","namespace":"dev"},"boundapps":null}
```
vs `/api/v1/namespaces/<ns>/services/<service name>`
```
{"user":"my-epinio-user","details":{"a":"a"}}
```
**Desktop/CLI (please complete the following information):**
 - Epinio Version: 0.1.6

**Comment by kkaempf** [comment] 2021-11-12 15:14
@richard-cox is this blocking Beta3 release ?

**Comment by richard-cox** [comment] 2021-11-12 17:28
@kkaempf It should do, though that's a long way off. In terms of beta2 i don't think so, unless there's objections from @agracey ?
As it stands
- Users can't edit 'data' for existing services
- After navigating to a service in the ui and refreshing the page the user will see a forever loading indicator

**Comment by andreas-kupries** [comment] 2021-11-22 10:34
@richard-cox Please add your thoughts about the spec below:

----
### Current State Of The Service Responses

The relevant types are `ServiceResponseList`, `ServiceResponse`, and `ServiceShowResponse`.

The last is the data for an individual service.  The first is an array of the second, the data for a set of services.

In detail

```
type ServiceResponseList []ServiceResponse

type ServiceResponse struct {
	Meta      ServiceRef `json:"meta"`
	BoundApps []string   `json:"boundapps"`
}

type ServiceShowResponse struct {
	Username string            `json:"user"`
	Details  map[string]string `json:"details,omitempty"`
}
```

### Proposed changes

First, extend the `ServiceResponse` with a `Spec` field, of type `ServiceShowResponse`. That should cover most of the things desired by the ticket.

```
type ServiceResponse struct {
	Meta      ServiceRef          `json:"meta"`
	BoundApps []string            `json:"boundapps"`
	Spec      ServiceShowResponse `json:"spec"`
}
```

The issue is the bound apps information ... Currently supplied for the list of services no such information is available when asking for a single service.

This can be fixed by moving that field into the `ServiceShowResponse`, i.e. the `Spec`.
This would look like:

```
type ServiceResponseList []ServiceResponse

type ServiceResponse struct {
	Meta      ServiceRef          `json:"meta"`
	Spec      ServiceShowResponse `json:"spec"`
}

type ServiceShowResponse struct {
	Username string            `json:"user"`
	Details  map[string]string `json:"details,omitempty"`
	BoundApps []string         `json:"boundapps"`
}
```

The disadvantage of doing this is that retrieving the data for a single service will become slower. Because that query would now have to query the kube for the service/app mapping. This currently involves asking for all apps, their services, and inverting that (*).

The two `services` endpoints asking for all services (in a namespace) are able to amortize that, as they ask for this mapping once, and then simply scatter the information to all the `ServiceResponses`.

If that change is made then asking for many services is very likely better done by asking for all and then filtering client side to the desired subset (matching names by glob pattern?), than asking individually.

Because the latter would incur the service/app overhead in each call, instead of once for all services.

---
(*) The knowledge of which apps and services are bound is currently stored only in the apps, implicitly, in the mountpoints to the service secrets.

    The service resources have no information about which apps they are bound to.

    Putting such information somewhere, to make the service -> apps query as fast as an app -> services query, runs the risk of desynching from the primary source I described 2 paragraphs above.

**Closed** 2021-11-24 14:48 UTC
Labels: bug, milestone3
